### ISSUE TITLE
Source code for version 2.1

### ISSUE THREAD

**Issue by fabiodiluca** [castleproject/ActiveRecord#5]
Hi, this is not really an issue, sorry to open it here.
But I wonder if somebody still have the source code for version 2.1 of ActiveRecord?
It would be very helpful to me. 
Thanks in advance!

**Comment by mausch** [comment]
Hi, here's the tag for 2.1.2 : https://github.com/castleproject-deprecated/Castle.ActiveRecord-READONLY/releases/tag/2.1.2

**Comment by stakx** [comment]
That should be in the commit history. I don't know this project, but it might be roughly around the time of this commit: https://github.com/castleproject-deprecated/ActiveRecord/commit/154daeeb99593fcb0e30ab9684cb276f6b541af0

**Comment by fabiodiluca** [comment]
Thanks, I appreciate your help.
